// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/lookup-gene.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var CIVIC_URL = "https://civicdb.org/api/graphql";
var DGIDB_URL = "https://dgidb.org/api/graphql";
var MYGENE_URL = "https://mygene.info/v3/query";
async function gql(url, query, variables) {
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, variables })
    });
    if (!res.ok) return null;
    const json = await res.json();
    if (json.errors) return null;
    return json.data;
  } catch {
    return null;
  }
}
var lookup_gene_default = defineTool({
  name: "lookup_gene",
  title: "Look up gene annotations",
  description: "Fetch cancer-focused annotations for a human gene symbol (HGNC). Returns metadata (name, Entrez/Ensembl IDs, summary), CIViC clinical-evidence count, and DGIdb drug interactions.",
  inputSchema: {
    symbol: z.string().min(1).describe("HGNC gene symbol, e.g. TP53, BRCA1, EGFR.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ symbol }) => {
    const sym = symbol.trim().toUpperCase();
    const [civic, dgidb, mygeneRes] = await Promise.all([
      gql(
        CIVIC_URL,
        `query ($s: [String!]) { genes(entrezSymbols: $s, first: 5) { nodes { name fullName description entrezId stats { evidenceItemCount } } } }`,
        { s: [sym] }
      ),
      gql(
        DGIDB_URL,
        `query ($n: [String!]!) { genes(names: $n) { nodes { name longName geneCategories { name } interactions { drug { name } } } } }`,
        { n: [sym] }
      ),
      fetch(
        `${MYGENE_URL}?q=symbol:"${sym}"&species=human&fields=symbol,name,summary,entrezgene,ensembl.gene,type_of_gene&size=1`
      ).then((r) => r.ok ? r.json() : null).catch(() => null)
    ]);
    const civicNode = civic?.genes.nodes.find((n) => n.name.toUpperCase() === sym) ?? civic?.genes.nodes[0];
    const dgidbNode = dgidb?.genes.nodes.find((n) => n.name.toUpperCase() === sym) ?? dgidb?.genes.nodes[0];
    const mygeneHit = mygeneRes?.hits?.[0];
    const drugs = Array.from(new Set((dgidbNode?.interactions ?? []).map((i) => i.drug.name).filter(Boolean)));
    const categories = Array.from(new Set((dgidbNode?.geneCategories ?? []).map((c) => c.name).filter(Boolean)));
    const ensemblId = mygeneHit?.ensembl && (Array.isArray(mygeneHit.ensembl) ? mygeneHit.ensembl[0]?.gene : mygeneHit.ensembl.gene);
    const result = {
      symbol: sym,
      officialSymbol: mygeneHit?.symbol ?? civicNode?.name ?? sym,
      fullName: mygeneHit?.name ?? civicNode?.fullName ?? dgidbNode?.longName ?? null,
      description: mygeneHit?.summary ?? civicNode?.description ?? null,
      entrezId: mygeneHit?.entrezgene ? String(mygeneHit.entrezgene) : civicNode?.entrezId ? String(civicNode.entrezId) : null,
      ensemblId: ensemblId ?? null,
      geneType: mygeneHit?.type_of_gene ?? null,
      civicEvidenceCount: civicNode?.stats.evidenceItemCount ?? 0,
      dgidbDrugCount: drugs.length,
      dgidbDrugs: drugs.slice(0, 50),
      dgidbCategories: categories,
      externalLinks: {
        civic: civicNode ? `https://civicdb.org/genes/${civicNode.name}` : null,
        dgidb: dgidbNode ? `https://dgidb.org/genes/${dgidbNode.name}` : null,
        ncbi: mygeneHit?.entrezgene ? `https://www.ncbi.nlm.nih.gov/gene/${mygeneHit.entrezgene}` : null,
        ensembl: ensemblId ? `https://www.ensembl.org/id/${ensemblId}` : null,
        genecards: `https://www.genecards.org/cgi-bin/carddisp.pl?gene=${sym}`
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/lookup-genes-batch.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var CIVIC_URL2 = "https://civicdb.org/api/graphql";
var DGIDB_URL2 = "https://dgidb.org/api/graphql";
async function gql2(url, query, variables) {
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, variables })
    });
    if (!res.ok) return null;
    const json = await res.json();
    if (json.errors) return null;
    return json.data;
  } catch {
    return null;
  }
}
var lookup_genes_batch_default = defineTool2({
  name: "lookup_genes_batch",
  title: "Look up multiple genes (compact)",
  description: "Return compact CIViC evidence counts and DGIdb drug counts for up to 40 HGNC gene symbols in one call. Useful for triaging a cohort of genes.",
  inputSchema: {
    symbols: z2.array(z2.string().min(1)).min(1).max(40).describe("Up to 40 HGNC gene symbols.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ symbols }) => {
    const syms = Array.from(new Set(symbols.map((s) => s.trim().toUpperCase()))).filter(Boolean);
    const [civic, dgidb] = await Promise.all([
      gql2(
        CIVIC_URL2,
        `query ($s: [String!]) { genes(entrezSymbols: $s, first: 200) { nodes { name stats { evidenceItemCount } } } }`,
        { s: syms }
      ),
      gql2(
        DGIDB_URL2,
        `query ($n: [String!]!) { genes(names: $n) { nodes { name interactions { drug { name } } } } }`,
        { n: syms }
      )
    ]);
    const civicMap = /* @__PURE__ */ new Map();
    for (const n of civic?.genes.nodes ?? []) civicMap.set(n.name.toUpperCase(), n.stats.evidenceItemCount);
    const dgidbMap = /* @__PURE__ */ new Map();
    for (const n of dgidb?.genes.nodes ?? []) {
      const drugs = new Set(n.interactions.map((i) => i.drug.name).filter(Boolean));
      dgidbMap.set(n.name.toUpperCase(), drugs.size);
    }
    const results = syms.map((s) => ({
      symbol: s,
      civicEvidenceCount: civicMap.get(s) ?? 0,
      dgidbDrugCount: dgidbMap.get(s) ?? 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qjcyoccdquidylaufinc";
var mcp_default = defineMcp({
  name: "oncogene-annotator-mcp",
  title: "OncoGene Annotator",
  version: "0.1.0",
  instructions: "Cancer-gene annotation tools. Use `lookup_gene` for a single HGNC symbol (full metadata + CIViC evidence + DGIdb drugs). Use `lookup_genes_batch` for compact counts across up to 40 symbols. Data comes from public sources (CIViC, DGIdb, MyGene.info) and is for research use only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [lookup_gene_default, lookup_genes_batch_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
